### ISSUE TITLE
SMW Sandbox is down

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/semantic-mediawiki.org#101]
Nothing new, just thought it might be a good idea to document this here, in case anybody else is wondering.

Any news on getting the sandbox up and running again, @kghbln ?

**Comment by kghbln** [comment]
Not yet. The holdup is converting the current Chameleon 1.x skin into Chameleon 4.x including SARS and whatever. The Chameleon releases were unfortunately made without the option of a shim. Tough titties for early Chameleon adaptors.

Duplicate of https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/92

**Comment by kghbln** [comment]
@krabina Will a blank new sandbox help you or are you seeking for something that was on the sandbox wiki?

**Comment by krabina** [comment]
No, I was trying to look up something from an older issue in sandbox.

**Comment by krabina** [comment]
why don't you bring it to life with vector skin for the time being?

**Comment by kghbln** [comment]
> No, I was trying to look up something from an older issue in sandbox.

That's what I thought. The reason why I have not yet just created a blank sandbox.

**Comment by kghbln** [comment]
> why don't you bring it to life with vector skin for the time being?

To be able to bring up the sandbox easily I need to upgrade the server. To be able to upgrade the server I need to make sure that Chameleon on s-mw.o works which will not be the case. The issue is not Chameleon on sandbox. Could not care less about Chameleon on sandbox. It all boils down to converting Chameleon 1 to 3 or 4 for smw.o. All the rest should be fairly fast unless some unexpected happens. Anyhow I really need to put this on the front burner.
