### ISSUE TITLE
Backup?

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#23]
Do we have a backup plan? It would be a shame if things like below vanish in thin air due to a missing backup.

- https://sandbox.semantic-mediawiki.org/wiki/Module:Comic_books
- https://sandbox.semantic-mediawiki.org/wiki/Module:Person
- ...

**Comment by kghbln** [comment]
Indeed. Currently I do a weekly backup (files, sql dump, xml dump) and sync this to my home computer. Hover it may by a good idea to do a daily backup and additionally sync the stuff over to "stetsonia" since sandbox has grown beyond its initial scope.

**Comment by mwjames** [comment]
> Hover it may by a good idea to do a daily backup and additionally sync the stuff over to "stetsonia" since sandbox has grown beyond its initial scope.

In terms of "disaster recovery", maybe have a document somewhere on how to revive those backups.

**Comment by kghbln** [comment]
> In terms of "disaster recovery", maybe have a document somewhere on how to revive those backups.

Yes, this should be documented with a minimum info where to find the files.

**Comment by kghbln** [comment]
Just changed from a weekly to a daily backup. Still to do is to automatically rsync the stuff to stetsonia and to document where the files are located.

**Comment by kghbln** [comment]
@mwjames @JeroenDeDauw Finally I solved this.

The fourteen daily backups for both websites for file-, sql- and xml-dumps are rotated daily on a first in first out basis. There are stored on both servers since I rsync them aroung though the downloads are made available via the official server and not my private one.

**Comment by kghbln** [comment]
One note: We do not really follow the [3-2-1 rule](http://blog.trendmicro.com/trendlabs-security-intelligence/world-backup-day-the-3-2-1-rule/) here since we store only in one format unless one of you decides to burn the backup to a DVD or so. However we have three copies on three locations since I also sync with my home PC.
