### ISSUE TITLE
Website outage (10 Jan 2017 - 11 Jan 2017) post-mortem

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#24]
With reference to [0, 1, 2] maybe a quick analysis as to what caused the outage and some suggestions on how to recover more quickly given that several people reported [1, 2] the issue, yet only after 24h the website regained an accessibly state.

[2] has noted:

> I guess this is a DOS attack. The VM should be rebooted and see if this makes them back off.

- Was it a DOS attack or an internal issue with the software?
- In case it was a DOS, was the website vulnerable to a certain type of DOS (some ports remained open etc.)?
- Do we know the a reason why the automatic reboot didn't took place (maybe due to some missing configuration)?
- In case the situation arises again in future and someone is unable to intervene maybe a redirect to something like [3] should be provided temporarily

[0] http://wikimedia.7.x6.nabble.com/Website-outage-td5070738.html
[1.0] https://twitter.com/Brynnan/status/819403187006427137
[1.1] https://twitter.com/Dinoguy1000/status/819217886204018690
[1.2] https://twitter.com/brunoo_gonzalez/status/819139473946578944
[2] https://www.mediawiki.org/wiki/Topic:Tiwx2m13uu3qyooh
[3] https://web.archive.org/web/20161231021251/https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki

**Comment by JeroenDeDauw** [comment]
No idea what happened. Server was shut down. I started it again and all was fluff.

**Comment by kghbln** [comment]
Sorry, I did not see this until now since I do not get notifications from GitHub for new issues. :(

> No idea what happened. Server was shut down.

I do not think that it was really shut down. In this case I expect to get a refused connection right away. Till the end the attempts to connect timed out. Also we did not receive any warnings from the monitoring system so there must have been something alive.

> Was it a DOS attack or an internal issue with the software?

Still have to verify with the log. We had two attacks last year from an IP supposedly originating from Paris, France.

> Do we know the a reason why the automatic reboot didn't took place

Afaik there is no automatic reboot. This has to be triggered manually via the ISPs customer interface which I do not have access to.

> I started it again and all was fluff.

Unfortunately my e-mails to Jeroen ended up in the spam folder so me asking for action was basically voided. So we had a combination of several unfortunate events. As always then things are bellies up. O_o

Otherwise the outage would have just been a couple of hours. Started at 4 am and I learned about it a 8 am without Titter, e-mails or posts..

**Comment by kghbln** [comment]
I guess what happened is that the server just hang itself up together with the vm. Happened to sandbox last week, too. I thought that it might have been some kind of DOS however the webserer's logs do no support this. So, yeah, just restarting the vm solve the issue, a task currently only @JeroenDeDauw can do.

**Comment by mwjames** [comment]
>  solve the issue, a task currently only @JeroenDeDauw can do.

Yeah to the [bus factor](https://en.wikipedia.org/wiki/Bus_factor)! There should be at least another person, right?
