### ISSUE TITLE
Using fixed tables?

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/semantic-mediawiki.org#25]
Using fixed properties ($sespUseAsFixedTables = 'true';) is recommended in the docs for SESP. In the light of https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/14, however, I'm wondering if this is fine for SMW 2.4.4.

**Comment by mwjames** [comment]
>Using fixed properties ($sespUseAsFixedTables = 'true';) is recommended in the docs for SESP. In the light of #14, however, I'm wondering if this is fine for SMW 2.4.4.

The setting `sespUseAsFixedTables` relates to pre-defined properties while  #14 is made in reference to user-defined properties which has some issues and got fixed in 2.5.

The method used to create "Fixed property" tables for pre-defined properties is different from that of user-defined properties (due to "free" label, typing etc.) therefore using `sespUseAsFixedTables` is fine for any SMW release and we advise users to read [0] when it comes to user-defined properties.

[0] https://www.semantic-mediawiki.org/wiki/Help:Fixed_properties

**Comment by D-Groenewegen** [comment]
Thanks for clarifying this distinction!
