### ISSUE TITLE
Mailing lists down?!

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#44]
My release announcement for https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2996 did not get through yet and it is no longer possible to subscribe to a mailing list.

[Ticket 16426](https://sourceforge.net/p/forge/site-support/16426/)

**Comment by kghbln** [comment]
@JeroenDeDauw @mwjames FYI

**Comment by JeroenDeDauw** [comment]
The last mail I got was on February 12th. Not good :(

**Comment by ivanhercaz** [comment]
I have experimented the same issue... Yesterday I sent a mail with a proposal, today I await an answer at least of @kghbln, because I know that he reads all the mails hehe, but for my surprise, I have not any mail in my inbox. I checked the archive in Sourceforge and I confirmed that my mail did not send to the mailing list. This is a very bad new for us :(

One question, would not it be better to have the lists configured on the server with GNU Mailman?

**Comment by ivanhercaz** [comment]
Just now I have received an «Delivery Status Notification» that reports the mail could not be delivered, but the system will continue retrying it, with the next error:

> 451 Temporary local problem - please try later

Maybe it could be added to the report made by @kghbln to make easier the solution for the Sourceforge's team.

**Comment by JeroenDeDauw** [comment]
> One question, would not it be better to have the lists configured on the server with GNU Mailman?

Would it be possible to migrate the existing lists to such a setup, or would people need to resubscribe?

If this is better and someone is willing to setup and maintain this, I suspect it would be good to do it on a dedicated server, and not add extra stuff to the one hosting the website. That presumably allows keeping the website one properly locked down. Then again I'm really not an ops person so what do I know.

**Comment by ivanhercaz** [comment]
> Would it be possible to migrate the existing lists to such a setup, or would people need to resubscribe?

Of course, setup the mailing list without Sourcefourge only would be possible if it is possible to make a backup of suscribers and the archives. If not, it would not be a good way.

**Comment by kghbln** [comment]
They served us for 13 years now for free so I think it is acceptable to have an issue for a couple of days. However if it takes longer we have to think of something else. My idea would be to ask if WMF provides a mailing list for us (at the same time merging user and devel since the latter has only marginal activity for quite some time now). Other projects like foreground use a WMF mailing list, too. Anyways lets give SourceForge a chance to get their act together. Other projects are affected too as I could see from other reports rolling in.

**Comment by ivanhercaz** [comment]
My question about the own mailing lists arose from this issue, but I did not propose it because Sourceforge have failed after 13 years. It only was a doubt :) Neither I pretended to urge the gave up of Sourceforge's mailing list. Excuse me for the misunderstanding!

I like your idea in the case the error will not solved soon, some weeks in my opinion. Great idea!

**Comment by kghbln** [comment]
Well, an own mailing list and migrating to it is still one of the options. However before we get this rolling we should give them a chance.

**Comment by ivanhercaz** [comment]
Totally agree, @kghbln. Change for this issue is not reasonable, I think.

**Comment by kghbln** [comment]
Good news. SourceForge fixed the issue. The mails got through now, it is possible to subscribe again and paradise was regained.

Now I am up for Twitter related topics? ;) :) @JeroenDeDauw

**Comment by JeroenDeDauw** [comment]
![Paradise.png](https://user-images.githubusercontent.com/146040/36309355-90a42a16-1324-11e8-9cfa-b4527185e628.png)
