### ISSUE TITLE
Sandbox needs carrot

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/semantic-mediawiki.org#49]
![image](https://user-images.githubusercontent.com/146040/43377905-d992bee8-93c3-11e8-911a-b65e30e3612f.png)

**Comment by JeroenDeDauw** [comment]
Else it can't run the latest Maps version :)

**Comment by kghbln** [comment]
> Else it can't run the latest Maps version :)

The switch to PHP 7.1 comes to early as far as I am concerned. Sandbox is running the latest debian which comes with PHP 7.0 and the next debian release which will come with PHP 7.2 is not expected before mid 2019. So we cannot test latest Maps there. :|

**Comment by JeroenDeDauw** [comment]
Security support for PHP 7.0 will be stopped in 4 months, so I'm not inclined to do extra effort to support it in new versions of Maps. People can still run the current latest release of Maps. Unlike their obsolete PHP release their Maps release will still get security fixes :)

**Comment by JeroenDeDauw** [comment]
How many carrots (twenny bars) do you want for the 7.1 upgrade? :D

Btw I've been thinking of having a dedicated Maps documentation wiki. Not sure if that is feasible without much administration overhead though.

**Comment by kghbln** [comment]
> How many carrots (twenny bars) do you want for the 7.1 upgrade? :D

It's not just a matter of carrots. I also would like this server to have the same setup as my production servers when it comes to general software. This helps me test better and see what things are possible or not. Moreover I do not like the idea of installing or removing multiple versions of PHP since I am not a master system admin. It is the details that cause the pain and consume time you do not really have.

> Btw I've been thinking of having a dedicated Maps documentation wiki. Not sure if that is feasible without much administration overhead though.

The only advantage I see is that it would allow to run master and serve as a sandbox at the same time. Yes I could do this but we have to decide on a sub-domain, like e.g. <mapping.wikiproject.net> for I domain in our control.

Note: https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/46 still to do for this to work.

**Comment by kghbln** [comment]
> Security support for PHP 7.0 will be stopped in 4 months, so I'm not inclined to do extra effort to support it in new versions of Maps.

No issue with this. In the end you are the one doing an effort to provide good software. I am only puzzled that PHP developers do not even try to align with Debian. We are talking about a market share of 25 % here. Ok, Ubuntu is up to speed with a share of 35 % but another 35 % is using even older PHP versions. So the project does not even serve close to 50 %. Anyways they will probably know better what they are doing. Refs https://w3techs.com/technologies/details/os-linux/all/all

> Unlike their obsolete PHP release their Maps release will still get security fixes :)

This will be highly appreciated on the light of the above.

**Comment by JeroenDeDauw** [comment]
> It is the details that cause the pain and consume time you do not really have.

I know right. Needing to tell them carrots apart is annoying :)

![image](https://user-images.githubusercontent.com/146040/43450387-e909c5c0-94b2-11e8-9a04-5e7e3c2bca4a.png)

> The only advantage I see is that it would allow to run master and serve as a sandbox at the same time. 

The main advantage is for the user: they would not easily end up on pages unrelated to Maps. Navigation would be easier.

> Yes I could do this but we have to decide on a sub-domain, like e.g. <mapping.wikiproject.net> for I domain in our control.

\o/ Would that work with a domain like mapsextension.com if I get that?

**Comment by JeroenDeDauw** [comment]
Just spend 1.5 hours upgrading my servers Ubuntu to have recent PHP, since some WP extension needed CURL and for some reason that was not working with PHP 5.6. I am now a 1337 sysadmin!

**Comment by kghbln** [comment]
> Just spend 1.5 hours upgrading my servers Ubuntu to have recent PHP, since some WP extension needed CURL and for some reason that was not working with PHP 5.6. I am now a 1337 sysadmin!

So you can feel the pain, though it does not seem to have been a difficulty, i.e. changes in PHP versions, etc. Usually this runs smooth. I have made the experience that Ubuntu only updates the core php-modules and removes the rest so you have to add php-curl etc. in a second step. Happend to me at the last upgrade of the server.

> \o/ Would that work with a domain like mapsextension.com if I get that?

Yes this would work too. You just have to add the server's IP to the A-Record of the domain. I personally would go for <maps-extension.net> since I do not really like .com (fits even less). The hyphen would make it a bit more easy to grasp what will be going on.

**Comment by JeroenDeDauw** [comment]
Ubuntu 18.10 comes with PHP 7.2 if I am not mistaken. Though Sandbox runs Debian right? On what server is the thing anyway? OSDA server? Same one as smworg? Or on kgh wiki farm?

**Comment by kghbln** [comment]
> Ubuntu 18.10 comes with PHP 7.2 if I am not mistaken. Though Sandbox runs Debian right?

Affirmative. I planned the upgrade already: https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/46

> On what server is the thing anyway? OSDA server? Same one as smworg? Or on kgh wiki farm?

See the [readme](https://github.com/SemanticMediaWiki/semantic-mediawiki.org/blob/master/README.md) ;)

**Comment by kghbln** [comment]
This will also be done by moving to a bionic server. There we will be getting the PHP 7.2 carrot. :) #52

**Comment by JeroenDeDauw** [comment]
![tenor](https://user-images.githubusercontent.com/146040/55199631-f9e7dd80-51ba-11e9-8353-8dc6f8737728.gif)
