### ISSUE TITLE
Wiki: Incomplete Installation Instructions

### ISSUE THREAD

**Issue by DynAggelos** [SemanticMediaWiki/semantic-mediawiki.org#54]
I just have one important suggestion for the page [Installation with shell access using Composer (MediaWiki 1.25+)](https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_Composer_with_MediaWiki_1.25%2B):

In the first callout under the Using Composer header, you should add instructions to run `php composer.phar install` for people who aren't already familiar with composer.

**Comment by kghbln** [comment]
Thanks for the note. I think that these instructions need to be reworked completely since they are basically defying reality. The best way to install SMW is adding or adapting the "composer.local.json" file followed by running `composer update --no-dev` as described [here](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md) No require, no install, no whatever ...

**Comment by kghbln** [comment]
I have just [updated](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AInstallation%2FUsing_Composer_with_MediaWiki_1.25%2B&type=revision&diff=69104&oldid=67586) the docu on the wiki. I believe to the better.
