### ISSUE TITLE
Provide a SMW bundle

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#55]
On the new server I will provide a bundle (individual file release) containing the latest stable LTS of MW including some SMW extensions for easy download. It appears that creating an individual file release itself is already a big obstacle. Now that we load via extension registration it is actually a feasible option.

**Comment by mwjames** [comment]
> On the new server I will provide a bundle (individual file release)
> containing the latest stable LTS of MW including some SMW extensions for
> easy download. It appears that creating an individual file release itself is
> already a big obstacle.

About how many users we are talking here? Does this justify binding
volunteer time on updating the bundle for each release change and each
component?

Providing such service opens a security attack vector (especially when
you want to bundle it with MW) which I honestly like to avoid since
the uploader would be held responsible in case of some breach (e.g
server that holds these files or the build that produces the bundle).

Yes, providing sufficient support for people to run the software is
paramount but should this project encourage or nurture a behaviour
where users are absolved from the responsibility of installing
components as documented [0, 1]?

Rather than providing yet another zip/tarball service where people are
going to complain that something is missing or packages being
outdated, I'd rather see the project to provide a docker bundle that
contains release references to components (not files) with the
security aspect being shifted to the docker environment rather having
project members to worry (or care) for bundling those components.

[0] https://github.com/SemanticMediaWiki/IndividualFileRelease
[1] https://www.semantic-mediawiki.org/wiki/Help:Installation/Quick_guide

Cheers

**Comment by kghbln** [comment]
> About how many users we are talking here?

Well, I do not have exact numbers but I have a feeling that these numbers are higher than we think.

> Does this justify binding volunteer time on updating the bundle for each release change and each component?

I was thinking about an automated daily creation of an individual file release.

> Providing such service opens a security attack vector.

That's true. I had this in mind but figured that a disclaimer would be enough.

> Rather than providing yet another zip/tarball service where people are going to complain that something is missing or packages being outdated, I'd rather see the project to provide a docker bundle that contains release references to components (not files) with the security aspect being shifted to the docker environment rather having project members to worry (or care) for bundling those components.

Docker will not help the people in need of an individual file release, however having yet another zip/tarball is too much in the end. This is why we finally dropped support for this. Besides, it is already a big issue to get Docker running on Linux Mint, which I found hilarious. Still, such a Docker service will be the way

Anyhow, I think in about one to tow years MediaWiki itself will no longer be installable from a tar and if we are frank it does not really make sense already today.
