### ISSUE TITLE
Less Semantic MediaWiki recorded on WikiApiary

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/semantic-mediawiki.org#65]
Refs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4173#issuecomment-520196480

I see five reasons (sorted by importance) why the numbers shown [here](https://sandbox.semantic-mediawiki.org/wiki/Semantic_MediaWiki_Usage) are in decline:

1. One has to register at WikiApiary to add a wiki. I believe that this is too much of an effort. 
2. The numbers on WikiApiary are bloated by the dominance of Referata websites from the start. Since this farm is deteriorating it looses a lot of users recently.
3. I am no longer super active on this wiki, meaning that I myself do not add as many wikis as before.
4. There is a tendency to use SMW in disclosed environments rather than for public wikis, at least where I am in direct contact
5. The Cargo extension turned some users away.
6. The Wikibase extension may turned some users away.

**Comment by krabina** [comment]
I would also add that usage of Wikibase outside of Wikimedia projects has become an issue, eg. in some digital humanities projects. I strongly believe it is not due to considering both SMW and Wikibase and then deciding for Wikibase, but due to the knowledge about Wikidata trying to use Wikibase for other usecases without any knowledge about SMW.

**Comment by mwjames** [comment]
> I would also add that usage of Wikibase outside of Wikimedia projects has
> become an issue, eg. in some digital humanities projects. I strongly believe
> it is not due to considering both SMW and Wikibase and then deciding for
> Wikibase, but due to the knowledge about Wikidata trying to use Wikibase for
> other usecases without any knowledge about SMW.

Besides the brand that says Wikipedia powered Wikidata and a dedicated
development team that caters for the product 7x24h, it is
understandable that institutional users want to be on the safe side
and decide for something like Wikidata (Wikibase) instead of a
homegrown extension to MediaWiki that most of these users never heard
of.

One of the reason I mentioned  SMM + Wikibase on the SMWCon 2019 issue
thread [0] was actually that "if you can't beat them, join them"
because we cannot guarantee a 7x24h development support. So, the
question arises of what would be the benefits of joining forces (SMM +
Wikibase) on a MediaWiki installation? What are strength and
weaknesses where both would (or could) complement each other that
would make sense to those users groups.

## Questions

Some oversimplified questions which should be extended.

- How difficult is it to run both SMM + Wikibase on an instance?
- What are the direct benefits (features) of SMW over Wikibase?
- What are the benefits of Wikibase over SMW?
- Where do both complement each other?
- Any special customizing that needs SMW to implement to make running
both (SMM + Wikibase) as easy as walking in the park (property
namespace comes to mind etc.)?
- Can we draw some conclusions or lessons learned from https://nimiarkisto.fi/?
- What are the distinct needs for institutional users to run Wikibase?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4173

Cheers

**Comment by krabina** [comment]
I guess the ideal person to answer the technical questions is @JeroenDeDauw ;-)

I would add: 
How can we make sure that SMW is better known and that people considering Wikibase for their projects also consider SMW?

**Comment by kghbln** [comment]
> I would also add that usage of Wikibase outside of Wikimedia projects has become an issue

I'd personally add this as point 6 of importance to my list, which I will do.

**Comment by mwjames** [comment]
On 8/12/19, Bernhard Krabina <notifications@github.com> wrote:
> I guess the ideal person to answer the technical questions is @JeroenDeDauw
> ;-)

Yes,and ask @Nikerabbit about his experience because he is the only
user I know of that runs SMW + Wikibase together.

> How can we make sure that SMW is better known and that people considering
> Wikibase for their projects also consider SMW?

You got the venue (SMWCon), make use of it! You should set aside a
time slot to discuss this issue (and above questions) maybe allowing
to devise an action plan and operational strategy of how to answer
some of those questions.

**Comment by JeroenDeDauw** [comment]
I'm very skeptical about Wikibase having much of an impact on SMW at this point. There has been a lot of success theater from the Wikimedia side but where are the successful Wikibase adoptions?

[Not many Wikibase installs out there](https://wikibase-registry-query.wmflabs.org/#%23defaultView%3ATimeline%0ASELECT%20%3Fitem%20%3FitemLabel%20%3FcreationDate%20%28SAMPLE%28%3Flogo%29%20AS%20%3Fimage%29%0AWHERE%0A%7B%0A%20%20%20%20%3Fitem%20wdt%3AP11%20wd%3AQ20%20.%0A%20%20%20%20%3Fitem%20wdt%3AP5%20%3FcreationDate%20.%0A%09SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22%20%7D%0A%20%20%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP8%20%3Flogo%20%7D%0A%7D%0AGROUP%20BY%20%3Fitem%20%3FitemLabel%20%3FcreationDate). Note how many of the entries there just error and others are dead wikis.

---

> a dedicated development team that caters for the product 7x24h

There is most certainly no 24x7 support for third parties. There are not even stable releases and upgrade instructions. It has been like that for a long time. Tells you about WMDEs priorities, which are fair enough, though that raises some ethics questions about WMDE pushing Wikibase onto third party users.

**Comment by mwjames** [comment]
> point. There has been a lot of success theater from the Wikimedia side but
> where are the successful Wikibase adoptions?

I don't know which is why I raised the question. As for the "success
theater", I don't think I find a lot of stories like [0] in regards to
SMW, so yes, visibility and communication do create impressions and
shape perception.

> There is most certainly no 24x7 support for third parties. There are not
> even stable releases and upgrade instructions. It has been like that for a

Of course there isn't but as an allegory it should bring the attention
of matters for institutional users meaning to have a constant stream
of developers available for product development compared to SMW which
has ~0 FTE as reliable support source.

[0] https://blog.wikimedia.de/2019/05/09/new-testing-ground-for-wikibase-a-federal-agency-goes-on-an-expedition-in-the-wiki-universe/

**Comment by JeroenDeDauw** [comment]
That story is from the WMDE hot air machine. I'm really unhappy about what happened there in the last year since I think a number of third parties have been mislead.

You can't compare the FTE the Wikibase team has with that of SMW. The FTE from the Wikibase team go to features for Wikidata. And a huge portion of that is in firefighting, dealing with bureaucratic nonsense and being slowed down by increasing lack of architecture. As mentioned, there are not even stable releases and upgrade instructions. That is how many FTE there are for third party concerns.

The main effort going into third parties is from the communication people, not from the dev team.

If adoption of SMW is a concern then I'd not pay too much attention to things like Wikibase and Cargo. At least not besides seeing if there are interesting innovations that make sense also adopting. Instead I'd focus on pulling more people into the enterprise wiki world. The pie is very small at the moment and can be grown a lot.

**Comment by krabina** [comment]
For reference: https://meta.wikimedia.org/wiki/Wikidata/Strategy/2019

**Comment by JeroenDeDauw** [comment]
https://upload.wikimedia.org/wikipedia/commons/c/cc/Strategy_for_Wikibase_Ecosystem.pdf

> In 2018 the number of existing Wikibase installations nearly doubled

At least this is qualified a bit more further down:

> Between 2012 and 2017,12 Wikibase instances were created. But in 2018 alone 11 new instances were set up.

What this fails to mention is that half those new instances are now down, half of the remainder are WMF run test wikis and only 3 have any activity on them.
